/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Ad: typeof import('./src/components/shop/ad.vue')['default']
    Adminbuyrecord: typeof import('./src/components/admin/adminbuyrecord.vue')['default']
    Adminshoppingbag: typeof import('./src/components/admin/adminshoppingbag.vue')['default']
    Back: typeof import('./src/components/system/back.vue')['default']
    Buynew: typeof import('./src/components/shop/buynew.vue')['default']
    Buyrecord: typeof import('./src/components/center/buyrecord.vue')['default']
    Classitem: typeof import('./src/components/shop/classitem.vue')['default']
    Classlist: typeof import('./src/components/shop/classlist.vue')['default']
    Clear: typeof import('./src/components/system/clear.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Footer: typeof import('./src/components/system/footer.vue')['default']
    Header: typeof import('./src/components/system/header.vue')['default']
    Headeradmin: typeof import('./src/components/system/headeradmin.vue')['default']
    Headercenter: typeof import('./src/components/system/headercenter.vue')['default']
    Hotwupinlist: typeof import('./src/components/shop/hotwupinlist.vue')['default']
    Rightwin: typeof import('./src/components/system/rightwin.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/shop/search.vue')['default']
    Shoppingbag: typeof import('./src/components/center/shoppingbag.vue')['default']
    Usertitleadmin: typeof import('./src/components/system/usertitleadmin.vue')['default']
    Usertitlecenter: typeof import('./src/components/system/usertitlecenter.vue')['default']
    Wechat: typeof import('./src/components/system/wechat.vue')['default']
    Wupinitem: typeof import('./src/components/shop/wupinitem.vue')['default']
    Wupinlist: typeof import('./src/components/shop/wupinlist.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
